services:
  postgres:
    image: postgres:15-alpine
    container_name: diagmod_postgres_dev
    environment:
      POSTGRES_DB: diagmod
      POSTGRES_USER: diagmod_user
      POSTGRES_PASSWORD: diagmod_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
      - ./sql/schema:/docker-entrypoint-initdb.d/01-schema:ro
      - ./sql/views:/docker-entrypoint-initdb.d/02-views:ro
      - ./sql/procedures:/docker-entrypoint-initdb.d/03-procedures:ro
      - ./sql/seed:/docker-entrypoint-initdb.d/04-seed:ro
      - ./configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diagmod_user -d diagmod"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - diagmod_network

  redis:
    image: redis:7-alpine
    container_name: diagmod_redis_dev
    command: >
      redis-server
      --appendonly no
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --timeout 300
    volumes:
      - ./docker_data/redis:/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - diagmod_network

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: development
      args:
        INSTALL_DEV: "1"
        LIGHT_DEPS: "1"
    environment:
      REDIS_URL: "redis://redis:6379/0"
      CELERY_BROKER_URL: "redis://redis:6379/1"
      CELERY_RESULT_BACKEND: "redis://redis:6379/2"
      APP_ENVIRONMENT: development
      DATABASE_URL: postgresql+asyncpg://diagmod_user:diagmod_password@postgres:5432/diagmod
      LOG_LEVEL: DEBUG
      API_RELOAD: "true"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - diagmod_network

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
      target: development
      args:
        INSTALL_DEV: "0"
        LIGHT_DEPS: "1"
    environment:
      REDIS_URL: "redis://redis:6379/0"
      CELERY_BROKER_URL: "redis://redis:6379/1"
      CELERY_RESULT_BACKEND: "redis://redis:6379/2"
      APP_ENVIRONMENT: development
      DATABASE_URL: postgresql+asyncpg://diagmod_user:diagmod_password@postgres:5432/diagmod
      LOG_LEVEL: DEBUG
      CELERY_WORKER_CONCURRENCY: 2
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
    command: ["python", "-m", "celery", "-A", "src.worker.celery_app", "worker", "--loglevel=debug", "--concurrency=2"]
    depends_on:
      - postgres
      - redis
    networks:
      - diagmod_network

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile
      target: development
      args:
        LIGHT_DEPS: "1"
    environment:
      API_URL: http://api:8000
      LOG_LEVEL: DEBUG
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./logs:/app/logs
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - diagmod_network

  prometheus:
    image: prom/prometheus:latest
    container_name: diagmod_prometheus_dev
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.retention.time=72h"
      - "--storage.tsdb.retention.size=1GB"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./configs/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_dev_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - diagmod_network

  grafana:
    image: grafana/grafana:latest
    container_name: diagmod_grafana_dev
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SECURITY_DISABLE_GRAVATAR: "true"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
    volumes:
      - grafana_dev_data:/var/lib/grafana
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - diagmod_network

  jupyter:
    build:
      context: .
      dockerfile: docker/jupyter/Dockerfile
    container_name: diagmod_jupyter
    environment:
      DATABASE_URL: postgresql+asyncpg://diagmod_user:diagmod_password@postgres:5432/diagmod
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - "8888:8888"
    command: ["python", "-m", "jupyterlab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--notebook-dir=/app"]
    depends_on:
      - postgres
      - redis
    networks:
      - diagmod_network

  loader:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: development
    working_dir: /app
    command: ["bash"]
    environment:
      DATABASE_URL: postgresql+asyncpg://diagmod_user:diagmod_password@postgres:5432/diagmod
      REDIS_URL: redis://redis:6379/0
      LOG_LEVEL: DEBUG
    volumes:
      - ./data:/data:ro  # безопасный относительный путь
    depends_on:
      - postgres
      - redis
    networks:
      - diagmod_network
    profiles:
      - loader

volumes:
  prometheus_dev_data:
  grafana_dev_data:

networks:
  diagmod_network:
    external: false
